# ---------------------------------------------------------------
# variables
root_dir=${PWD}

# ---------------------------------------------------------------
# keep current website as backup
mv ./book ./book.sav

# ---------------------------------------------------------------
# PRE BUILD SCRIPTS
cd ${root_dir}/scripts

# update the glossary to each src/*.md page
python3 -m glossary.py

cd ${root_dir}
# ---------------------------------------------------------------
# BUILD SCRIPTS
cd ${root_dir}/scr/en/stable
mdbook build ${root_dir}/book/en/stable

# ---------------------------------------------------------------
# POST BUILD SCRIPTS
cd ${root_dir}/scripts

# add the dropdown "Version" on each *.html page generated by mdbook
python3 -m version.py
# add the dropdown "Langage" on each *.html page generated by mdbook
python3 -m langage.py
# fix link format (remove '.html' endings for external links)
python3 -m link.py

# back to root folder
cd ${root_dir}

ln -s ${PWD}/media/ ${PWD}/book/media


