# move temporary to the script folder
cd scripts

# add the dropdown "Version" on each *.html page generated by mdbook
python3 -m version.py
# add the dropdown "Langage" on each *.html page generated by mdbook
python3 -m langage.py
# fix link format (remove '.html' endings for external links)
python3 -m link.py

# back to root folder
cd ..