# move temporary to the script folder
pushd ./scripts

# add the dropdown "Version" on each *.html page generated by mdbook
python3 -m version.py
# fix link format (remove '.html' endings for external links)
python3 -m link.py

# back to root folder
popd